config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:create, :new] do
    collection do
      post :logout
    end
  end

  scope '/admin' do
    resources :locations
    post "new_location", to: 'locations#create'

    resources :appointments do
      collection {post :import }
    end
    post "new_appointment", to: 'appointments#create'
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'admin' => 'admin#index'
    get 'providers' => 'providers#index'
    get  'static_pages/about'
    get  'static_pages/help'
    get  'static_pages/disclaimer'
    get  'static_pages/news'

    get '/:locale' => 'feed#index'
    root 'feed#index'
  end
end

app/views/shared/_footer.html.erb
<div class="mx-auto mb-2 flex justify-center border-t-2 border-gray-200">
  <hr/>
  <div class="flex flex-col items-center">
    <p class="mt-2 px-4 italic text-base md:text-base text-gray-600 text-center">
      <small>
        <%= t('partials.footer.message_a') %>
        <a
          class="text-red-400 hover:underline font-medium"
          target="_blank"
          rel="noopener noreferrer"
          href="https://rubyonrails.org/"
        >
          Ruby on Rails
        </a>
        <%= t('partials.footer.message_b') %>
        <a
          class="text-blue-400 hover:underline font-medium"
          target="_blank"
          rel="noopener noreferrer"
          href="https://tailwindcss.com/"
        >
          TailwindCSS
        </a>
        <%= t('partials.footer.message_c') %>
        <a
          class="text-purple-400 hover:underline font-medium"
          target="_blank"
          rel="noopener noreferrer"
          href="https://www.turbovax.info/about"
        >
          TurboVax
        </a>
        <%= t('partials.footer.message_d') %>
      </small>
    </p>
    <p class="mt-2 italic text-md md:text-md text-gray-600">
      <small>
        <%= link_to t('partials.footer.disclaimer'), static_pages_disclaimer_path, class: "hover:text-blue-600 font-medium underline" %>
      </small>
    </p>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="flex flex-col mx-auto max-w-7xl">
  <div class="flex justify-center mt-12">
    <h1 class="text-5xl font-semibold">VaxSpotter</h1>
  </div>
  <div class="flex justify-center text-xs space-x-4 pt-6">
    <div class="hover:underline hover:text-blue-600 "><%= link_to 'English', root_path(locale: :en) %></div>
    <div class="hover:underline hover:text-blue-600 "><%= link_to 'Español', root_path(locale: :es) %></div>
  </div>
  <nav class="pt-6 pb-8 flex justify-center space-x-6 text-xl font-light text-blue-700">
    <div class="lowercase"><%= link_to t('partials.header.home'), root_path, class: "hover:underline hover:text-blue-600" %></div>
    <div class="lowercase"><%= link_to t('partials.header.providers'), providers_path, method: "get", class: "hover:underline hover:text-blue-600" %></div>
    <div class="lowercase"><%= link_to t('partials.header.news'), static_pages_news_path, method: "get", class: "hover:underline hover:text-blue-600" %></div>
    <div class="lowercase"><%= link_to t('partials.header.about'), static_pages_about_path, class: "hover:underline hover:text-blue-600" %></div>
    <div class="lowercase"><%= link_to t('partials.header.help'), static_pages_help_path, class: "hover:underline hover:text-blue-600" %></div>
    <% if session[:current_user] %>
      <div><%= link_to "admin", "/admin", class: "hover:underline hover:text-blue-600" %></div>
      <div><%= link_to "locations", locations_path, method: "get", class: "hover:underline hover:text-blue-600" %></div>
      <div><%= link_to "appointments", appointments_path, method: "get", class: "hover:underline hover:text-blue-600" %></div>
    <% end %>
  </nav>
</div>

app/views/shared/_news_update.html.erb
<div class="rounded-md bg-gray-200 p-4">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-6 w-6 text-gray-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
      </svg>
    </div>
    <div class="ml-3 flex-1 md:flex-col md:justify-between">
      <p class="text-sm text-gray-800">
      <%= message %>
      </p>
      <p>
        <a target="_blank" rel="noopener noreferrer" href=<%=link%> class="text-xs hover:underline italic"><%=link%></a> 
      </p>
    </div>
  </div>
</div>

app/views/shared/_notification.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="rounded-md bg-blue-100 p-4">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3 flex-1 md:flex md:justify-between">
      <p class="text-sm text-blue-800">
      <%= message %>
      </p>
      <p class="mt-3 text-sm md:mt-0 md:ml-6 self-center">
        <a href=<%= url %> target="_blank" rel="noopener noreferrer" class="whitespace-nowrap font-medium text-blue-700 hover:text-blue-600"><%= t('partials.notification.details') %><span aria-hidden="true">&rarr;</span></a>
      </p>
    </div>
  </div>
</div>

app/views/shared/_update.html.erb
<div class="rounded-md bg-blue-200 px-4 py-1 w-full">
  <div class="flex">
    <div class="flex-shrink-0 self-center">
      <svg class="h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3 flex-1 md:flex-col md:justify-between">
      <p class="text-sm text-blue-800">
      <%= message %>
      </p>
    </div>
  </div>
</div>