config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:create, :new] do
    collection do
      post :logout
    end
  end

  scope '/admin' do
    resources :locations
    post "new_location", to: 'locations#create'

    resources :appointments do
      collection {post :import }
    end
    post "new_appointment", to: 'appointments#create'
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'admin' => 'admin#index'
    get 'providers' => 'providers#index'
    get  'static_pages/about'
    get  'static_pages/help'
    get  'static_pages/disclaimer'
    get  'static_pages/news'

    get '/:locale' => 'feed#index'
    root 'feed#index'
  end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :location
  after_save_commit :build_publish_tweet

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Appointment.create! row.to_hash
    end
  end

  private

  def build_publish_tweet
    if self.is_stale == true
      return puts "Will not tweet about saving/updating an appt to stale = true"
    end

    location = Location.where("id = ?", self.location_id).first

    if self.start_time && self.end_time
      appt_times = "  #{self.start_time.strftime("%l:%M%P")} - #{self.end_time.strftime("%l:%M%P")}"
    else
      appt_times = ""
    end

    if self.vaccines_available
      vaccines_available = "  (#{self.vaccines_available} availble)"
    else
      vaccines_available = ""
    end

    time_now = Time.zone.now.strftime("%l:%M%P").strip
    appt_date = "#{self.date.strftime("%b %d")}"
    tweet = "(#{time_now}) spotted availability at 👇\n\n#{location.name}\n#{location.address}\n\nAppointments on: #{appt_date}\n\nUse the link below to reserve a spot!\n\n#{location.appointment_url}"

    if Rails.env.production?
      TweetJob.perform_now(tweet)
    else
      puts '=================================================='
      puts tweet
      puts '==================  NEXT TWEET  =================='
    end


  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:edit, :update, :destroy]

  def index
    @appointments = Appointment.where("appointments.date >= ?", Time.now).order("date DESC")
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      redirect_to appointments_path, notice: "Successfully Added A New appointment"
    else
      render :new
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path, notice: "Successfully Deleted The appointment"
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to appointments_path, notice: "Successfully Edited The appointment"
    else
      render :edit
    end
  end

  def import
    Appointment.import(params[:file])
    redirect_to appointments_path, notice: "Successfully Imported Appointment CSV"
  end

  private

  def appointment_params
    params.require(:appointment).permit(:location_id, :date, :start_time, :end_time, :vaccines_available)
  end

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end
end

app/views/appointments/_form.html.erb
  <%= form_with model: @appointment do |form| %>
  <div class="flex flex-col">
    <% if @appointment.errors.any? %>
      <div class="p-4 bg-red-200 text-red-800 rounded">
        <h3 class="font-semibold pb-1">Please resolve the following errors:</h3>
        <% @appointment.errors.full_messages.each do |message| %>
          <div class="mt-1"><%= message %></div>
        <% end %>
      </div>
    <% end %>

  <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">

    <div class="sm:col-span-6 pb-3">
      <label for="location" class="block text-sm font-medium text-gray-700">
        Location <i class="text-blue-500">required</i>
      </label>
      <div class="mt-1">
        <%= form.select :location_id, Location.all.order('name ASC').collect { |p| ["#{p.name}: #{p.address}  ~>  id:#{p.id}", p.id] }, { :include_blank => true }, {class: "py-2 px-1 border border-gray-300 bg-white rounded-md focus:bg-white shadow block w-full sm:text-sm"} %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="date" class="block text-sm font-medium text-gray-700">
        Date <i class="text-blue-500">required</i>
      </label>
      <div class="mt-1">
        <%= form.date_field :date, class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="start_time" class="block text-sm font-medium text-gray-700">
        Start Time
      </label>
      <div class="mt-1">
        <%= form.time_field :start_time, class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="end_time" class="block text-sm font-medium text-gray-700">
        End Time
      </label>
      <div class="mt-1">
        <%= form.time_field :end_time, class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="vaccines_available" class="block text-sm font-medium text-gray-700">
        Vaccines Available
      </label>
      <div class="mt-1">
        <%= form.text_field :vaccines_available, class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>
  </div>

  <div class="mt-6">
    <%= form.submit "Submit Form", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
  </div>

  <% end %>
</div>

app/views/appointments/edit.html.erb
<div class="flex flex-col justify-center mx-auto max-w-3xl pb-24">
  <div class="pb-8">
    <h2 class="text-2xl leading-6 font-medium text-gray-900">Edit An Appointment</h2>
    <p class="mt-2 text-sm text-gray-500">
      Use this form to edit an existing appointment
    </p>
  </div>

  <%= render "form", appointment: @appointment %>

</div>

app/views/appointments/index.html.erb
<div class="flex flex-col mx-auto px-10">
  <div class="flex justify-between">
    <h1 class="text-2xl">List of Current & Future Appointments (Might be stale/taken)</h1>
    <div class="flex space-x-4">
      <%= button_to "Add New Appointment", new_appointment_path, method: "get", class: "group relative flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %> 
    </div>
  </div>
  <div class="mt-4">
    <% if @appointments.any? %>
      <div class="flex flex-col">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-y-auto border-b border-gray-200 sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200 table-auto">
                <thead class="bg-gray-200 sticky">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Date
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Stale
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Location Id
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Location
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Start Time
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      End Time
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Vaccines Available
                    </th>
                    <th scope="col" class="relative px-6 py-3">
                      <span class="sr-only">Edit</span>
                    </th>
                    <th scope="col" class="relative px-6 py-3">
                      <span class="sr-only">Delete</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  <% @appointments.each do |appointment| %>
                    <tr>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= appointment.date %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        <%= appointment.is_stale %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        <%= appointment.location_id %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        <%= Location.find(appointment.location_id).name %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= appointment.start_time %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= appointment.end_time %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= appointment.vaccines_available %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <%= link_to "Edit", edit_appointment_path(appointment), class: "text-indigo-600 hover:text-indigo-900" %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <%= link_to "Delete", appointment_path(appointment), method: "delete", data: { confirm: "Are you sure?" }, class: "text-indigo-600 hover:text-indigo-900" %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="my-8">
    <h1 class="text-2xl mb-4">Bulk Appointment Import</h1>
      <%= form_tag import_appointments_path, multipart: true do %>
        <div class="max-w-xl flex justify-center px-6 pt-8 pb-8 border-2 border-gray-300 border-dashed rounded-md">
          <div class="space-y-3 text-center">
            <div class="flex text-sm text-gray-600 flex justify-center">
              <%= file_field_tag :file, class: "" %>
            </div>
            <div>
              <p class="text-sm text-gray-500">
                Headers: location_id*, date*, start_time, end_time, vaccines_available
              </p>
            </div>
          </div>
        </div>
        <%= submit_tag "Upload Appointments CSV", class: "mt-4 group relative flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>  
      <% end %>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="flex flex-col justify-center mx-auto max-w-3xl pb-24">
  <div class="pb-8">
    <h2 class="text-2xl leading-6 font-medium text-gray-900">Add A New Appointment</h2>
    <p class="mt-2 text-sm text-gray-500">
      Use this form to add a new appointment
    </p>
  </div>

  <%= render "form", appointment: @appointment %>

</div>