config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:create, :new] do
    collection do
      post :logout
    end
  end

  scope '/admin' do
    resources :locations
    post "new_location", to: 'locations#create'

    resources :appointments do
      collection {post :import }
    end
    post "new_appointment", to: 'appointments#create'
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'admin' => 'admin#index'
    get 'providers' => 'providers#index'
    get  'static_pages/about'
    get  'static_pages/help'
    get  'static_pages/disclaimer'
    get  'static_pages/news'

    get '/:locale' => 'feed#index'
    root 'feed#index'
  end
end

app/models/location.rb
class Location < ApplicationRecord
  validates :name, :address, :appointment_url, presence: true
  has_many :appointments, dependent: :destroy

  enum location_type: {
    medical_center: 1,
    super_station: 2,
    community_center: 3,
    pharmacy: 4,
  }
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_path, notice: "Successfully Added A New Location"
    else
      render :new
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_path, notice: "Successfully Deleted The Location"
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to locations_path, notice: "Successfully Edited The Location"
    else
      render :edit
    end
  end

  private

  def location_params
    params.require(:location).permit(:name, :address, :city, :appointment_url, :managed_by, :contact_email, :contact_phone, :is_walk_thru, :is_drive_thru, :location_type)
  end

  def set_location
    @location = Location.find(params[:id])
  end
end

app/views/locations/_form.html.erb
  <%= form_with model: @location do |form| %>
  <div class="flex flex-col">
    <% if @location.errors.any? %>
      <div class="p-4 bg-red-200 text-red-800 rounded">
        <h3 class="font-semibold pb-1">Please resolve the following errors:</h3>
        <% @location.errors.full_messages.each do |message| %>
          <div class="mt-1"><%= message %></div>
        <% end %>
      </div>
    <% end %>

  <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">

    <div class="sm:col-span-6 pb-3">
      <label for="name" class="block text-sm font-medium text-gray-700">
        Name <i class="text-blue-500">required</i>
      </label>
      <div class="mt-1">
        <%= form.text_field :name, class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="address" class="block text-sm font-medium text-gray-700">
        Address <i class="text-blue-500">required</i>
      </label>
      <div class="mt-1">
        <%= form.text_field :address, placeholder: "1234 Some Address St. San Diego, CA 92109", class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="city" class="block text-sm font-medium text-gray-700">
        City
      </label>
      <div class="mt-1">
        <%= form.text_field :city, placeholder: "Del Mar", class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="contact_phone" class="block text-sm font-medium text-gray-700">
        Location Type <i class="text-blue-500">required</i>
      </label>
      <div class="mt-1">
        <%= form.select :location_type, Location.location_types.keys.map { |lt| [lt.humanize, lt] }, { :include_blank => true }, { class: 'py-2 px-1 border border-gray-300 bg-white rounded-md focus:bg-white shadow block w-full sm:text-sm' } %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="appointment_url" class="block text-sm font-medium text-gray-700">
        Appointment URL <i class="text-blue-500">required</i>
      </label>
      <div class="mt-1">
        <%= form.text_field :appointment_url, placeholder: "https://www.schedule-appointment-with-us.com/parameters", class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="managed_by" class="block text-sm font-medium text-gray-700">
        Location Managed By (e.g. City of San Diego, Kaiser Health, or UCSD, etc.)
      </label>
      <div class="mt-1">
        <%= form.text_field :managed_by, class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="contact_email" class="block text-sm font-medium text-gray-700">
        Contact Email
      </label>
      <div class="mt-1">
        <%= form.text_field :contact_email, class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>

    <div class="sm:col-span-6 pb-3">
      <label for="contact_phone" class="block text-sm font-medium text-gray-700">
        Contact Phone Number
      </label>
      <div class="mt-1">
        <%= form.text_field :contact_phone, class: "py-2 px-1 border border-gray-300 rounded-md focus:bg-gray-200 shadow block w-full sm:text-sm" %>
      </div>
    </div>
  </div>

  <div class="mt-6">
    <fieldset>
      <legend class="text-base font-medium text-gray-900">
        Is the Vacccine Site Walk-thru and/or Drive-thru?
      </legend>
      <div class="mt-4 space-y-4">

        <div class="relative flex items-start">
          <div class="flex items-center h-5 mr-3">
            <%= form.label "Walk-thru" %> <br />
          </div>
          <div>
            <%= form.check_box :is_walk_thru, class: "h-4 w-4 border border-gray-300 rounded" %> <br />
          </div>
        </div>

        <div class="relative flex items-start">
          <div class="flex items-center h-5 mr-3">
            <%= form.label "Drive-thru" %> <br />
          </div>
          <div>
            <%= form.check_box :is_drive_thru, class: "h-4 w-4 border border-gray-300 rounded" %> <br />
          </div>
        </div>

      </div>
    </fieldset>
  </div>

  <div class="mt-6">
    <%= form.submit "Submit Form", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
  </div>

  <% end %>
</div>

app/views/locations/edit.html.erb
<div class="flex flex-col justify-center mx-auto max-w-3xl pb-24">
  <div class="pb-8">
    <h2 class="text-2xl leading-6 font-medium text-gray-900">Edit Location</h2>
    <p class="mt-2 text-sm text-gray-500">
      Edit an existing vaccine location
    </p>
  </div>

  <%= render "form", location: @location %>

</div>

app/views/locations/index.html.erb
<div class="flex flex-col mx-auto px-10">
  <div class="flex justify-between">
    <h1 class="text-2xl">List of Locations</h1>
    <%= button_to "Add New Location", new_location_path, method: "get", class: "group relative flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %> 
  </div>
  <div class="mt-4">
    <% if @locations.any? %>
      <div class="flex flex-col">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-200">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Name
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Address
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      City
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Location Type
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Appt. URL
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Managed By
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Email
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Phone
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Walk-thru
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                      Drive-thru
                    </th>
                    <th scope="col" class="relative px-6 py-3">
                      <span class="sr-only">Edit</span>
                    </th>
                    <th scope="col" class="relative px-6 py-3">
                      <span class="sr-only">Delete</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  <% @locations.each do |location| %>
                    <tr>
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        <%= location.name %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700 truncate">
                        <%= location.address %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= location.city %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= location.location_type.nil? ? location.location_type : location.location_type.humanize %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700 truncate">
                        <%= location.appointment_url %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= location.managed_by %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= location.contact_email %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= location.contact_phone %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= location.is_walk_thru %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-700">
                        <%= location.is_drive_thru %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <%= link_to "Edit", edit_location_path(location), class: "text-indigo-600 hover:text-indigo-900" %>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <%= link_to "Delete", location_path(location), method: "delete", data: { confirm: "Are you sure?" }, class: "text-indigo-600 hover:text-indigo-900" %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/locations/new.html.erb
<div class="flex flex-col justify-center mx-auto max-w-3xl pb-24">
  <div class="pb-8">
    <h2 class="text-2xl leading-6 font-medium text-gray-900">Add A New Location</h2>
    <p class="mt-2 text-sm text-gray-500">
      Use this form to add a new vaccine location
    </p>
  </div>

  <%= render "form", location: @location %>

</div>